### ISSUE TITLE
specifying optional dependencies

### ISSUE THREAD

**Issue by MaxEtMoritz** [IITC-CE/Community-plugins#13]
One of my Plugins has an optional dependency to another plugin: it runs without it, but is limited in features without that other plugin.

It would be nice to be able to mark a dependency as optional.

or should i just list that other plugin as "full" dependency, although that's not quite true?

Btw: will listing a dependency to a plugin that's not in the repo (yet) break everything (i assume yes)?

**Comment by modos189** [comment]
For optional dependencies, I suggest using the keyword "recommends" similar to "deps":
`recommends: name@author`
where _name_ is the name of the plugin file without _iitc_ and _plugin_

If the dependency plugin is not in the repository, the dependency will simply not be clickable
