### ISSUE TITLE
GAODE plugin: use china map offset code from IITC main?

### ISSUE THREAD

**Issue by Artoria2e5** [IITC-CE/Community-plugins#43]
The GAODE plugin by @GMOogway currently bundles its own equivalent of `fix-china-map-offset`. It should probably be changed to use the existing code in IITC main.

(It's not a fork of johnd0e's basemap-gaode.js.)

**Comment by modos189** [comment]
In this plugin collection, we just collect plugins from different authors. You can suggest a change to the plugin author or make a fork of the plugin

**Comment by Artoria2e5** [comment]
Fair enough, I should PR https://github.com/GMOogway/iitc-plugins instead.
